[Cocoa] Avoid NPE in Control.calculateVisibleRegion()
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSWindow.contentView()" because "window" is null
 at org.eclipse.swt.widgets.Control.calculateVisibleRegion(Control.java:775)
 at org.eclipse.swt.widgets.Control.getVisibleRegion(Control.java:2060)
 at org.eclipse.swt.widgets.Control.isObscured(Control.java:2341)
 at org.eclipse.swt.widgets.Scrollable.scrollClipViewToPoint(Scrollable.java:347)
 at org.eclipse.swt.widgets.Display.windowProc(Display.java:6754)

Fixes #614.
Fixes #472.
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=559198.