Bug 494151 - Eclipse crashes after displaying splash screen with java.lang.NoClassDefFoundError
Change sparc64 to sparcv9 so that the SWT fragment for SPARC is created
with 64-bit source code and not the 32-bit code

Change-Id: I5bff739a9bfe23c31bc1d6fb0970adcbdf81696b
Signed-off-by: Arun Thondapu <arunkumar.thondapu@in.ibm.com>