[Tests] Do not dispose SWT system colors
This is probably the reason for the following (on first sight unrelated)
test failure:
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4704)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.graphics.GC.setForeground(GC.java:3266)
	at org.eclipse.swt.custom.CTabFolderRenderer.drawSelected(CTabFolderRenderer.java:1487)
	at org.eclipse.swt.custom.CTabFolderRenderer.draw(CTabFolderRenderer.java:637)
	at org.eclipse.swt.custom.CTabFolder.onPaint(CTabFolder.java:2085)
    ...
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Native
Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_CTabFolder.processEvents(Test_org_eclipse_swt_custom_CTabFolder.java:295)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_CTabFolder.test_chevronAppearanceChanged(Test_org_eclipse_swt_custom_CTabFolder.java:261)

Change-Id: Ie7b8cea8ce273627cca5bac09aead58affdfdc89
Signed-off-by: Paul Pazderski <paul-eclipse@ppazderski.de>