[Linux] Fix natives build when NATIVE_STATS enabled
When native stats collection is enabled, i.e. by passing
`-DNATIVE_STATS` to the compiler then the natives fail to build:

```
os_stats.c:820: error: "NATIVE_FUNCTION_COUNT" redefined [-Werror]
  820 | #define NATIVE_FUNCTION_COUNT sizeof(GTK_nativeFunctionNames) /
      sizeof(char*)
os_stats.c:240: note: this is the location of the previous definition
  240 | #define NATIVE_FUNCTION_COUNT sizeof(GDK_nativeFunctionNames) /
      sizeof(char*)
```

This change causes the generator to prefix the NATIVE_FUNCTION_COUNT
macro name with the class whose native functions are being counted and
includes regenerated *_stats.c files.

The change also fixes up the NativeStats tool to know about the discrete
GTK libraries and allows native stats tool to be activated by environment
variable instead of requiring user to manually change the makefile.

Signed-off-by: Mat Booth <mat.booth@gmail.com>