Issue #448: [win32] ERROR_WIDGET_DISPOSED in StyledText when using Accessibility
There were two problems:
-- 1 --
Code in `StyledText.dispose()` was not called when `StyledText` was
disposed because its parent was disposed (that's the most common case).

Due to this problem, when an application cached `IAccessible2` pointer
and called it after `StyledText` was disposed, it resulted in errors
like
```
org.eclipse.swt.SWTException: code=24: Widget is disposed
	at org.eclipse.swt.SWT.error(SourceFile:4918)
	at org.eclipse.swt.SWT.error(SourceFile:4833)
	at org.eclipse.swt.SWT.error(SourceFile:4804)
	at org.eclipse.swt.widgets.Widget.error(SourceFile:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(SourceFile:369)
	at org.eclipse.swt.custom.StyledText.getCharCount(SourceFile:4022)
	at org.eclipse.swt.custom.StyledText$7.getCharacterCount(SourceFile:6824)
	at org.eclipse.swt.accessibility.Accessible.getCharacterCount(SourceFile:5016)
	at org.eclipse.swt.accessibility.Accessible.get_nCharacters(SourceFile:4649)
	at org.eclipse.swt.accessibility.Accessible$5.method17(SourceFile:375)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback17(SourceFile:219)
	at org.eclipse.swt.internal.win32.OS.PeekMessage
	at org.eclipse.swt.widgets.Display.readAndDispatch(SourceFile:3646)
```

-- 2 --
Not all `IAccessible` / `IAccessible2` methods had `.isDisposed()`
guards - in Bug 371326, only some methods were guarded (I understand
that only methods that had known Bugs against them).

Due to this problem, `Accessible` tried to do something on disposed
control and usually failed, returning weird errors like `E_INVALIDARG`.

Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>