Bug 497923 - [GTK] build.sh bugfixes and improvements
Part 2, Multiple new improvements:
This is a relatively large patch that adds additional parameter support.
Features:
* Build Gtk2 and Gtk3 can *both* be built via a single command:
 ./build.sh -gtk-all install
  This replaces the tedious process of having to:
 - In Eclipse, clean project, build Gtk2,
 - In Eclipse, clean Project, build Gtk3,
 - manually copy '*.so' files to binary repository.
* Help parameter (-h, --help) that explains parameters
* Gtk2/Gtk3 can be selected via: "-gtk2, -gtk3"flags
* 'echo now print in color. Green for general msgs, red for error
* Added error check for binary repository:
	If user specifies 'install' flag, which normally copies compiled
	*.so files to binary repo, but folder/binary repo does not exist,
	then user is warned and the script exits with error.
* JAVA_HOME fix: build.sh often fails on fresh systems because 
  JAVA_HOME is not set. JAVA_HOME is usually blank on most systems.
  The failure usually reads:
	swt.h:23:17: fatal error: jni.h: No such file or directory
	compilation terminated.
  This patch dynamically acquires JAVA_HOME based on the location of
  the 'java' executable. This works on Fedora 24 and on Ubuntu 16
  (and probably on other systems).

1) Check out this patch
2) Clean your binary repository
3) Clean and rebuild your SWT project
4) Navigate to:
cd ~/git/eclipse.platform.swt/bundles/org.eclipse.swt/bin/library
(NOT the build.sh in .../Eclipse SWT PI/gtk/library/build.sh)
5) run:
	build.sh -gtk-all install
6) Build should succeed, print should output in color.
7) Navigate to your binary repository, ensure the following are built:
	git status
	...
	libswt-atk-gtk-4702.so
	libswt-awt-gtk-4702.so
	libswt-cairo-gtk-4702.so
	libswt-glx-gtk-4702.so
	libswt-gnome-gtk-4702.so
	libswt-gtk-4702.so
	libswt-pi-gtk-4702.so
	libswt-pi3-gtk-4702.so
	libswt-webkit-gtk-4702.so

execute:
	export JAVA_HOME=""   #if not already blank.
	./build.sh
Before the patch the above should fail with missing 'include jni.h',
after patch, everything should compile fine.

* Note, I also tested with maven, works fine. I did the following:
cd
~/git/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.gtk.linux.x86_64
mvn clean verify -Pbuild-individual-bundles -Dnative=gtk.linux.x86_64

Change-Id: I1b934a7ab95a8e0d00bd8e685db86fbaa7465bdf
Signed-off-by: Lev Ufimtsev <lufimtse@redhat.com>